version: '3'

services:
  app:
    build:
      context: .
      args:
        - REACT_APP_BACKEND_HOST=api.espcd.duckdns.org
        - REACT_APP_BACKEND_SECURE=true
        - REACT_APP_BACKEND_PORT=443
    restart: unless-stopped
    ports:
      - "80:80"
