name: Docker build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image job
    steps:
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            REACT_APP_BACKEND_HOST=api.espcd.duckdns.org
            REACT_APP_BACKEND_SECURE=true
            REACT_APP_BACKEND_PORT=443
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
